version: '3'
services:
  vscode-python:
    build:
      context: .
      dockerfile: Dockerfile.devel
    image: vscode-python:dev
    container_name: "vscode-python"
    expose:
      - "8080"
    volumes:
      - ./workspace:/workspace
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=123456
    command: /bin/bash -c "code-server --bind-addr 0.0.0.0:8080"